package au.com.roningroup.patrollink;

import android.content.*;
import android.content.res.AssetFileDescriptor;
import android.media.*;
import android.net.Uri;
import android.os.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;
import java.util.concurrent.*;

/**
 * Single-voice Patrol Link speech engine.
 *
 * Hard rule: Patrol Link never falls back to Android system TTS. Every spoken word in a live
 * announcement is generated by the currently selected cloned voice. If that voice is not
 * prepared or the voice service is unavailable, Patrol Link stays silent and monitoring
 * continues normally.
 */
public final class VoiceManager {
    public static final String DEFAULT_ID = "felicity";
    public static final String DEFAULT_NAME = "Felicity";
    private static final String PREF_PROFILES = "voice_profiles_v2";
    private static final String PREF_ACTIVE = "voice_profile_active";
    private static final String PREF_FELICITY_CLOUD_ID = "felicity_cloud_voice_id";
    private static final long BASE_DURATION_MS = 308_290L;
    private static final long MAX_IMPORT_BYTES = 120L * 1024L * 1024L;
    private static final String API_ROOT = "https://api.elevenlabs.io/v1";
    private static final String TTS_MODEL = "eleven_multilingual_v2";

    public interface ResultCallback { void done(boolean ok, String message); }

    public static final class Profile {
        public final String id, name, path, cloudVoiceId;
        public final long durationMs;
        public final boolean builtIn;
        Profile(String id,String name,String path,long durationMs,boolean builtIn,String cloudVoiceId) {
            this.id=id; this.name=name; this.path=path; this.durationMs=durationMs;
            this.builtIn=builtIn; this.cloudVoiceId=cloudVoiceId==null?"":cloudVoiceId;
        }
        public boolean prepared() { return !cloudVoiceId.isEmpty(); }
    }

    private static final class Announcement {
        final String token, text;
        Announcement(String text) { this.token=UUID.randomUUID().toString(); this.text=text; }
    }

    private final Context context;
    private final SharedPreferences prefs;
    private final SecretStore secret;
    private final Handler handler = new Handler(Looper.getMainLooper());
    private final ExecutorService io = Executors.newSingleThreadExecutor();
    private final ArrayDeque<Announcement> queue = new ArrayDeque<>();
    private Announcement current;
    private MediaPlayer player;
    private File playingFile;
    private volatile String lastError="";

    public VoiceManager(Context context,SharedPreferences prefs) {
        this.context=context.getApplicationContext();
        this.prefs=prefs;
        this.secret=new SecretStore(this.context,prefs);
        SharedPreferences.Editor e=prefs.edit();
        if(!prefs.contains(PREF_ACTIVE)) e.putString(PREF_ACTIVE,DEFAULT_ID);
        if(!prefs.getBoolean("voice_v119_migrated",false))
            e.putBoolean("voice",true).putBoolean("voice_v119_migrated",true);
        e.apply();
    }

    public String activeName() { return activeProfile().name; }
    public boolean apiConfigured() { return secret.has(); }
    public boolean ready() { return apiConfigured() && activeProfile().prepared(); }
    public String lastError() { return lastError; }

    public List<Profile> profiles() {
        ArrayList<Profile> out=new ArrayList<>();
        out.add(new Profile(DEFAULT_ID,DEFAULT_NAME,null,BASE_DURATION_MS,true,
                prefs.getString(PREF_FELICITY_CLOUD_ID,"")));
        try {
            JSONArray arr=new JSONArray(prefs.getString(PREF_PROFILES,"[]"));
            for(int i=0;i<arr.length();i++) {
                JSONObject o=arr.optJSONObject(i); if(o==null) continue;
                String id=o.optString("id"),name=o.optString("name"),path=o.optString("path");
                String cloud=o.optString("cloudVoiceId","");
                long d=o.optLong("duration",0);
                if(id.isEmpty()||name.isEmpty()||path.isEmpty()||d<=0) continue;
                if(new File(path).isFile()) out.add(new Profile(id,name,path,d,false,cloud));
            }
        } catch(Exception ignored) {}
        return out;
    }

    public Profile activeProfile() {
        String wanted=prefs.getString(PREF_ACTIVE,DEFAULT_ID);
        for(Profile p:profiles()) if(p.id.equals(wanted)) return p;
        prefs.edit().putString(PREF_ACTIVE,DEFAULT_ID).apply();
        return profiles().get(0);
    }

    public void setActive(String id) {
        for(Profile p:profiles()) if(p.id.equals(id)) {
            prefs.edit().putString(PREF_ACTIVE,id).apply();
            stop();
            lastError="";
            return;
        }
    }

    public void saveApiKey(String key) throws Exception {
        String clean=key==null?"":key.trim();
        if(clean.length()<16) throw new IllegalArgumentException("Enter a valid ElevenLabs API key.");
        secret.put(clean);
        lastError="";
    }

    public void clearApiKey() {
        stop();
        secret.clear();
        lastError="Voice API key not configured.";
    }

    public Profile importTrainingAudio(Uri uri,String requestedName) throws Exception {
        if(uri==null) throw new IllegalArgumentException("Choose an audio file.");
        String name=requestedName==null?"":requestedName.trim();
        if(name.isEmpty()||name.length()>40) throw new IllegalArgumentException("Voice name must be 1 to 40 characters.");
        File dir=new File(context.getFilesDir(),"voice_profiles");
        if(!dir.exists()&&!dir.mkdirs()) throw new IOException("Could not create the voice library.");
        String id="voice-"+UUID.randomUUID();
        File dest=new File(dir,id+".audio");
        long total=0;
        try(InputStream in=context.getContentResolver().openInputStream(uri);OutputStream out=new FileOutputStream(dest)) {
            if(in==null) throw new IOException("The selected audio file could not be opened.");
            byte[] buf=new byte[64*1024]; int n;
            while((n=in.read(buf))!=-1) {
                total+=n;
                if(total>MAX_IMPORT_BYTES) throw new IOException("Voice audio is larger than 120 MB.");
                out.write(buf,0,n);
            }
        } catch(Exception e) { dest.delete(); throw e; }
        long duration=duration(dest.getAbsolutePath());
        if(duration<30_000L||duration>600_000L) {
            dest.delete();
            throw new IllegalArgumentException("Use a clean voice recording between 30 seconds and 10 minutes.");
        }
        JSONArray arr=loadJson();
        JSONObject o=new JSONObject();
        o.put("id",id); o.put("name",name); o.put("path",dest.getAbsolutePath());
        o.put("duration",duration); o.put("cloudVoiceId","");
        arr.put(o);
        prefs.edit().putString(PREF_PROFILES,arr.toString()).putString(PREF_ACTIVE,id).apply();
        stop();
        return new Profile(id,name,dest.getAbsolutePath(),duration,false,"");
    }

    public boolean delete(String id) {
        if(id==null||DEFAULT_ID.equals(id)) return false;
        JSONArray old=loadJson(),next=new JSONArray(); boolean removed=false;
        for(int i=0;i<old.length();i++) {
            JSONObject o=old.optJSONObject(i); if(o==null) continue;
            if(id.equals(o.optString("id"))) {
                new File(o.optString("path","")).delete();
                removed=true;
            } else next.put(o);
        }
        if(removed) {
            SharedPreferences.Editor e=prefs.edit().putString(PREF_PROFILES,next.toString());
            if(id.equals(prefs.getString(PREF_ACTIVE,DEFAULT_ID))) e.putString(PREF_ACTIVE,DEFAULT_ID);
            e.apply(); stop();
        }
        return removed;
    }

    public void prepareActiveVoice(ResultCallback callback) {
        final Profile p=activeProfile();
        if(!apiConfigured()) {
            deliver(callback,false,"Enter the ElevenLabs API key first.");
            return;
        }
        if(p.prepared()) {
            deliver(callback,true,p.name+" is already ready.");
            return;
        }
        io.execute(()->{
            try {
                String voiceId=cloneVoice(p);
                saveCloudVoiceId(p.id,voiceId);
                lastError="";
                deliver(callback,true,p.name+" is ready. All live announcements will use only this voice.");
            } catch(Exception ex) {
                lastError=safeMessage(ex);
                deliver(callback,false,"Could not prepare "+p.name+": "+lastError);
            }
        });
    }

    private void saveCloudVoiceId(String profileId,String cloudVoiceId) throws Exception {
        if(DEFAULT_ID.equals(profileId)) {
            prefs.edit().putString(PREF_FELICITY_CLOUD_ID,cloudVoiceId).apply();
            return;
        }
        JSONArray arr=loadJson();
        for(int i=0;i<arr.length();i++) {
            JSONObject o=arr.optJSONObject(i);
            if(o!=null&&profileId.equals(o.optString("id"))) o.put("cloudVoiceId",cloudVoiceId);
        }
        prefs.edit().putString(PREF_PROFILES,arr.toString()).apply();
    }

    public void speak(Observation o) {
        if(o==null||!ready()) {
            if(!ready()) lastError="Selected voice is not prepared. Voice output suppressed; no fallback voice was used.";
            return;
        }
        enqueue(new Announcement(fullReadout(clean(o.activity()),clean(o.locationLine()),clean(o.guard))));
    }

    static String fullReadout(String activity,String location,String guard) {
        StringBuilder b=new StringBuilder("Update available.");
        String spoken=spokenGuard(guard);
        if(!spoken.isEmpty()) b.append(' ').append(spoken).append('.');
        if(!activity.isEmpty()) b.append(' ').append(activity).append('.');
        if(!location.isEmpty()&&!containsNormalised(activity,location))
            b.append(' ').append(location).append('.');
        return b.toString().replace("..",".");
    }

    static String spokenGuard(String s) {
        if(s==null) return "";
        String[] parts=s.trim().split("\\.");
        ArrayList<String> out=new ArrayList<>();
        for(String raw:parts) {
            String p=raw.trim();
            if(p.isEmpty()) continue;
            String letters=p.replaceAll("[^A-Za-z]","");
            String digits=p.replaceAll("[^0-9]","");
            if(!letters.isEmpty()) {
                if(letters.length()==1) out.add(letters.toUpperCase(Locale.ROOT));
                else if(letters.equals(letters.toUpperCase(Locale.ROOT)))
                    out.add(letters.substring(0,1).toUpperCase(Locale.ROOT)+letters.substring(1).toLowerCase(Locale.ROOT));
                else out.add(letters);
            }
            if(!digits.isEmpty()) out.add(digits);
        }
        return String.join(" dot ",out);
    }

    private static boolean containsNormalised(String a,String b) {
        String aa=(a==null?"":a).toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]+","");
        String bb=(b==null?"":b).toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]+","");
        return !bb.isEmpty()&&aa.contains(bb);
    }

    private static String clean(String s) {
        return s==null?"":s.replace('\n',' ').replace('\r',' ').replaceAll("\\s+"," ").trim();
    }

    public void test() {
        if(!ready()) { lastError="Selected voice is not prepared. No fallback voice was used."; return; }
        enqueue(new Announcement("Felicity voice test. Full Patrol Link voice output is working."));
    }

    private synchronized void enqueue(Announcement a) {
        if(queue.size()>10) queue.pollFirst();
        queue.addLast(a);
        if(current==null) startNext();
    }

    private synchronized void startNext() {
        if(current!=null) return;
        current=queue.pollFirst();
        if(current==null) return;
        final Announcement item=current;
        io.execute(()->{
            try {
                Profile p=activeProfile();
                if(!p.prepared()||!apiConfigured()) throw new IOException("Selected voice is not prepared.");
                File audio=synthesise(p.cloudVoiceId,item.text);
                handler.post(()->playGenerated(item.token,audio));
            } catch(Exception ex) {
                lastError=safeMessage(ex);
                handler.post(()->finish(item.token));
            }
        });
    }

    private File synthesise(String voiceId,String text) throws Exception {
        File cached=cacheFile(voiceId,text);
        if(cached.isFile()&&cached.length()>1024) return cached;

        URL url=new URL(API_ROOT+"/text-to-speech/"+URLEncoder.encode(voiceId,"UTF-8")+"?output_format=mp3_44100_128");
        HttpURLConnection c=(HttpURLConnection)url.openConnection();
        c.setConnectTimeout(15_000); c.setReadTimeout(45_000); c.setRequestMethod("POST");
        c.setDoOutput(true); c.setRequestProperty("xi-api-key",secret.get());
        c.setRequestProperty("Content-Type","application/json");
        c.setRequestProperty("Accept","audio/mpeg");
        JSONObject body=new JSONObject();
        body.put("text",text);
        body.put("model_id",TTS_MODEL);
        JSONObject settings=new JSONObject();
        settings.put("stability",0.50); settings.put("similarity_boost",0.85);
        body.put("voice_settings",settings);
        byte[] payload=body.toString().getBytes(StandardCharsets.UTF_8);
        c.setFixedLengthStreamingMode(payload.length);
        try(OutputStream out=c.getOutputStream()) { out.write(payload); }

        int code=c.getResponseCode();
        if(code<200||code>=300) throw new IOException("Voice service returned HTTP "+code+readError(c));
        File dir=cached.getParentFile(); if(!dir.exists()) dir.mkdirs();
        File temp=new File(dir,cached.getName()+".tmp");
        try(InputStream in=c.getInputStream();OutputStream out=new FileOutputStream(temp)) {
            byte[] buf=new byte[32*1024]; int n;
            while((n=in.read(buf))!=-1) out.write(buf,0,n);
        } finally { c.disconnect(); }
        if(temp.length()<1024) { temp.delete(); throw new IOException("Voice service returned empty audio."); }
        if(!temp.renameTo(cached)) {
            copy(temp,cached); temp.delete();
        }
        return cached;
    }

    private String cloneVoice(Profile profile) throws Exception {
        String boundary="----PatrolLink"+UUID.randomUUID().toString().replace("-","");
        URL url=new URL(API_ROOT+"/voices/add");
        HttpURLConnection c=(HttpURLConnection)url.openConnection();
        c.setConnectTimeout(20_000); c.setReadTimeout(90_000); c.setRequestMethod("POST");
        c.setDoOutput(true); c.setChunkedStreamingMode(64*1024);
        c.setRequestProperty("xi-api-key",secret.get());
        c.setRequestProperty("Content-Type","multipart/form-data; boundary="+boundary);
        try(OutputStream raw=c.getOutputStream();BufferedOutputStream out=new BufferedOutputStream(raw)) {
            writeField(out,boundary,"name",profile.name);
            writeField(out,boundary,"description","Patrol Link voice profile "+profile.name);
            if(profile.builtIn) {
                writeRawResource(out,boundary,"felicity_scan.ogg",R.raw.felicity_scan);
                writeRawResource(out,boundary,"felicity_breach.ogg",R.raw.felicity_breach);
                writeRawResource(out,boundary,"felicity_incident.ogg",R.raw.felicity_incident);
                writeRawResource(out,boundary,"felicity_generic.ogg",R.raw.felicity_generic);
            } else {
                writeFile(out,boundary,new File(profile.path),"voice-reference.audio");
            }
            out.write(("--"+boundary+"--\r\n").getBytes(StandardCharsets.UTF_8));
            out.flush();
        }
        int code=c.getResponseCode();
        if(code<200||code>=300) throw new IOException("Voice clone service returned HTTP "+code+readError(c));
        String response=readAll(c.getInputStream());
        c.disconnect();
        String voiceId=new JSONObject(response).optString("voice_id","");
        if(voiceId.isEmpty()) throw new IOException("Voice clone service did not return a voice ID.");
        return voiceId;
    }

    private void writeRawResource(OutputStream out,String boundary,String fileName,int resId) throws Exception {
        out.write(("--"+boundary+"\r\n").getBytes(StandardCharsets.UTF_8));
        out.write(("Content-Disposition: form-data; name=\"files\"; filename=\""+fileName+"\"\r\n").getBytes(StandardCharsets.UTF_8));
        out.write("Content-Type: audio/ogg\r\n\r\n".getBytes(StandardCharsets.UTF_8));
        try(InputStream in=context.getResources().openRawResource(resId)) { pipe(in,out); }
        out.write("\r\n".getBytes(StandardCharsets.UTF_8));
    }

    private static void writeFile(OutputStream out,String boundary,File file,String fileName) throws Exception {
        out.write(("--"+boundary+"\r\n").getBytes(StandardCharsets.UTF_8));
        out.write(("Content-Disposition: form-data; name=\"files\"; filename=\""+fileName+"\"\r\n").getBytes(StandardCharsets.UTF_8));
        out.write("Content-Type: application/octet-stream\r\n\r\n".getBytes(StandardCharsets.UTF_8));
        try(InputStream in=new FileInputStream(file)) { pipe(in,out); }
        out.write("\r\n".getBytes(StandardCharsets.UTF_8));
    }

    private static void writeField(OutputStream out,String boundary,String name,String value) throws Exception {
        out.write(("--"+boundary+"\r\n").getBytes(StandardCharsets.UTF_8));
        out.write(("Content-Disposition: form-data; name=\""+name+"\"\r\n\r\n").getBytes(StandardCharsets.UTF_8));
        out.write(value.getBytes(StandardCharsets.UTF_8));
        out.write("\r\n".getBytes(StandardCharsets.UTF_8));
    }

    private void playGenerated(String token,File file) {
        synchronized(this) {
            if(current==null||!current.token.equals(token)) return;
            try {
                releasePlayer();
                playingFile=file;
                MediaPlayer mp=new MediaPlayer(); player=mp;
                mp.setAudioAttributes(new AudioAttributes.Builder()
                        .setUsage(AudioAttributes.USAGE_ASSISTANCE_NAVIGATION_GUIDANCE)
                        .setContentType(AudioAttributes.CONTENT_TYPE_SPEECH).build());
                mp.setDataSource(file.getAbsolutePath());
                mp.setOnCompletionListener(x->finish(token));
                mp.setOnErrorListener((x,w,e)->{finish(token);return true;});
                mp.prepare(); mp.start();
                lastError="";
            } catch(Exception e) {
                lastError=safeMessage(e);
                finish(token);
            }
        }
    }

    private synchronized void finish(String token) {
        if(current==null||!current.token.equals(token)) return;
        releasePlayer();
        current=null;
        handler.post(this::startNext);
    }

    private void releasePlayer() {
        if(player!=null) {
            try{player.stop();}catch(Exception ignored){}
            try{player.release();}catch(Exception ignored){}
            player=null;
        }
        playingFile=null; // cache files are intentionally retained
    }

    public synchronized void stop() {
        queue.clear();
        releasePlayer();
        current=null;
    }

    public void shutdown() {
        stop();
        io.shutdownNow();
    }

    private File cacheFile(String voiceId,String text) throws Exception {
        File dir=new File(context.getCacheDir(),"voice_tts");
        return new File(dir,sha256(voiceId+"\n"+text)+".mp3");
    }

    private static String sha256(String s) throws Exception {
        MessageDigest d=MessageDigest.getInstance("SHA-256");
        byte[] hash=d.digest(s.getBytes(StandardCharsets.UTF_8));
        StringBuilder b=new StringBuilder();
        for(byte x:hash)b.append(String.format(Locale.ROOT,"%02x",x&0xff));
        return b.toString();
    }

    private static void copy(File a,File b) throws Exception {
        try(InputStream in=new FileInputStream(a);OutputStream out=new FileOutputStream(b)){pipe(in,out);}
    }

    private static void pipe(InputStream in,OutputStream out) throws Exception {
        byte[] buf=new byte[32*1024]; int n;
        while((n=in.read(buf))!=-1) out.write(buf,0,n);
    }

    private static long duration(String path) {
        MediaMetadataRetriever r=new MediaMetadataRetriever();
        try {
            r.setDataSource(path);
            String d=r.extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION);
            return d==null?0:Long.parseLong(d);
        } catch(Exception e) { return 0; }
        finally { try{r.release();}catch(Exception ignored){} }
    }

    private JSONArray loadJson() {
        try { return new JSONArray(prefs.getString(PREF_PROFILES,"[]")); }
        catch(Exception e) { return new JSONArray(); }
    }

    private static String readAll(InputStream in) throws Exception {
        ByteArrayOutputStream b=new ByteArrayOutputStream();
        pipe(in,b); return b.toString("UTF-8");
    }

    private static String readError(HttpURLConnection c) {
        try {
            InputStream in=c.getErrorStream();
            if(in==null)return "";
            String s=readAll(in).replaceAll("\\s+"," ").trim();
            return s.isEmpty()?"":": "+s.substring(0,Math.min(240,s.length()));
        } catch(Exception e){return "";}
    }

    private static String safeMessage(Exception e) {
        String m=e.getMessage();
        return m==null||m.trim().isEmpty()?e.getClass().getSimpleName():m.trim();
    }

    private void deliver(ResultCallback cb,boolean ok,String message) {
        if(cb!=null) handler.post(()->cb.done(ok,message));
    }
}
