from pathlib import Path
import shutil,sys,re
root=Path(sys.argv[1]);java=root/'app/src/main/java/au/com/roningroup/patrollink';payload=Path(__file__).parent

def rep(s,old,new):
    if old not in s: raise RuntimeError('Patch anchor missing: '+old[:180])
    return s.replace(old,new,1)

p=root/'app/build.gradle';s=p.read_text();s=rep(s,'versionCode 122','versionCode 123');s=rep(s,"versionName '1.1.12'","versionName '1.1.13'")
# Exact mode no longer needs the embedded synthesis AAR or huge model assets.
s=s.replace("    implementation files('libs/sherpa-onnx.aar')\n","")
s=s.replace("    implementation 'org.jetbrains.kotlin:kotlin-stdlib:2.2.0'\n","")
p.write_text(s)

for name in ['VoiceManager.java','ExactPhrasePack.java']:
    shutil.copyfile(payload/name,java/name)

# Exact website recording is authoritative: a full alert override is the complete spoken sentence.
p=java/'SpeechPreferences.java';s=p.read_text()
old='''    public synchronized String format(Observation row) {
        return SpeechRules.format(row,prefix(),nicknames(),overrides(ALERT),overrides(PLACE),overrides(PHRASE));
    }'''
new='''    public synchronized String format(Observation row) {
        Map<String,String> alerts=overrides(ALERT);
        String replacement=SpeechRules.clean(alerts.get(SpeechRules.key(row.issue)));
        if(!replacement.isEmpty()) {
            // User explicitly chose "say this instead": say exactly this and nothing else.
            return SpeechRules.phrases(replacement,overrides(PHRASE));
        }
        return SpeechRules.format(row,prefix(),nicknames(),alerts,overrides(PLACE),overrides(PHRASE));
    }'''
s=rep(s,old,new)
p.write_text(s)

# Replace voice-library import flow with exact phrase-pack workflow.
p=java/'MainActivity.java';s=p.read_text()
# Add request code if only legacy exists.
s=s.replace('private static final int REQ_VOICE_AUDIO = 4101;','private static final int REQ_VOICE_AUDIO = 4101;\n    private static final int REQ_EXACT_PACK = 4102;')

start=s.index('    private void voiceLibrary() {')
end=s.index('    private void diagnostics() {',start)
voice_ui=r'''    private void voiceLibrary() {
        LinearLayout form=vertical();form.setPadding(dp(20),dp(10),dp(20),dp(10));
        VoiceManager.Profile active=engine.voices.activeProfile();
        form.addView(text("ACTIVE VOICE",11,MUTED,true));gap(form,5);
        form.addView(text(active.name,24,WHITE,true));gap(form,6);
        form.addView(text(engine.voices.status(),12,engine.voices.ready()?ACCENT:AMBER,true));gap(form,12);
        form.addView(text("Exact recording mode: Patrol Link does not clone, reconstruct or synthesise this voice. It plays only audio generated by your voice website. No ElevenLabs, Android TTS or substitute voice is used.",12,MUTED,false));gap(form,12);

        for(VoiceManager.Profile profile:engine.voices.profiles()){
            boolean selected=profile.id.equals(active.id);
            addCard(form,button((selected?"●  ":"○  ")+profile.name,selected,()->{engine.voices.setActive(profile.id);toast(profile.name+" selected.");}));
        }

        addCard(form,button("Copy exact phrase-pack script",true,()->{
            String script=engine.voices.exactPackScript(engine.recent(),engine.guards());
            ((ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText(active.name+" exact phrase pack",script));
            toast("Exact "+active.name+" phrase-pack script copied. Generate it exactly on AnyVoiceLab, including every [pause 3].");
        }));

        addCard(form,button("Import exact AnyVoiceLab WAV",true,()->{
            Intent pick=new Intent(Intent.ACTION_OPEN_DOCUMENT);pick.addCategory(Intent.CATEGORY_OPENABLE);pick.setType("audio/wav");
            try{startActivityForResult(pick,REQ_EXACT_PACK);}catch(ActivityNotFoundException e){toast("No file picker is installed.");}
        }));

        addCard(form,button("Test exact voice",false,()->{
            if(!engine.voices.ready())toast("Import the exact phrase-pack WAV first.");
            else engine.voices.test();
        }));

        addCard(form,button("Speech controls: wording, names and speed",false,()->new SpeechSettingsUi(this,engine).show()));
        addCard(form,button("Add another voice profile",false,this::addVoiceProfile));

        if(!active.builtIn){
            VoiceManager.Profile deleting=active;
            addCard(form,dangerButton("Delete "+deleting.name,()->new AlertDialog.Builder(this).setTitle("Delete "+deleting.name+"?")
                .setMessage("Delete this local exact voice pack and profile?")
                .setPositiveButton("Delete",(d,w)->{engine.voices.delete(deleting.id);toast("Voice deleted. Felicity selected.");})
                .setNegativeButton("Cancel",null).show()));
        }

        ScrollView scroll=new ScrollView(this);scroll.addView(form);
        new AlertDialog.Builder(this).setTitle("Exact voice library").setView(scroll).setPositiveButton("Close",null).show();
    }

    private void addVoiceProfile(){
        EditText name=new EditText(this);name.setSingleLine(true);name.setHint("Voice name");name.setTextColor(WHITE);name.setHintTextColor(MUTED);
        AlertDialog d=new AlertDialog.Builder(this).setTitle("Add voice profile")
            .setMessage("Create the profile first. Then copy its phrase-pack script and generate that script with the voice you want.")
            .setView(name).setPositiveButton("Create",null).setNegativeButton("Cancel",null).create();
        d.setOnShowListener(v->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(x->engine.voices.importTrainingAudio(null,name.getText().toString(),(ok,msg)->{toast(msg);if(ok){d.dismiss();voiceLibrary();}})));
        d.show();
    }

    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data) {
        super.onActivityResult(requestCode,resultCode,data);
        if(requestCode==REQ_EXACT_PACK&&resultCode==RESULT_OK&&data!=null&&data.getData()!=null){
            android.net.Uri uri=data.getData();
            Toast.makeText(this,"Importing exact "+engine.voices.activeName()+" recordings…",Toast.LENGTH_LONG).show();
            engine.voices.importExactPack(uri,(ok,message)->{toast(message);if(ok)engine.voices.test();});
            return;
        }
        if(requestCode==REQ_VOICE_AUDIO&&resultCode==RESULT_OK&&data!=null&&data.getData()!=null){
            toast("This version uses exact phrase packs. Create a voice profile, copy its script, then import the AnyVoiceLab phrase-pack WAV.");
        }
    }

'''
s=s[:start]+voice_ui+s[end:]
# Help text.
s=s.replace('A bundled on-device speech model generates the complete guard, activity and property announcement using the selected local voice reference. Connection state is shown visually; the app does not repeatedly play connection-warning clips. Speech generation runs in a separate process from the 30-second monitor. The selected recording guides the voice; synthesis is not guaranteed to be identical to the original voice website.',
'''Exact voice mode plays only the recordings generated by your voice website. Copy the exact phrase-pack script from Voice settings, generate it with the selected website voice, preserving every [pause 3] separator, and import the resulting 16-bit PCM WAV. Patrol Link splits those deliberate pauses and maps the website recordings to the phrases. If a future alert or custom wording is not in the installed pack, the app stays silent for that update and tells you which exact recording is missing rather than substituting or reconstructing another voice.''')
p.write_text(s)

# Speech editor copy: make replacement semantics explicit.
p=java/'SpeechSettingsUi.java';s=p.read_text()
s=s.replace('Tap an alert to change how its complete title is spoken.','Tap an alert to replace the complete spoken announcement. If a replacement is saved, Patrol Link says only the replacement text — it does not add a guard, prefix or location unless you type them into that replacement.')
s=s.replace('Saved locally for speech only. Blank removes this override.','Saved locally for speech only. Blank removes this override. After adding new wording, copy and regenerate the exact phrase pack if that phrase is not already recorded.')
p.write_text(s)

# Remove local TTS service declaration if present.
p=root/'app/src/main/AndroidManifest.xml';s=p.read_text();s=re.sub(r'\s*<service android:name="\.LocalVoiceService"[^>]*/>\s*','\n        ',s);p.write_text(s)

# Tests.
unit=root/'app/src/test/java/au/com/roningroup/patrollink';instrument=root/'app/src/androidTest/java/au/com/roningroup/patrollink'
shutil.copyfile(payload/'ExactVoiceRulesTest.java',unit/'ExactVoiceRulesTest.java')
shutil.copyfile(payload/'ExactPhrasePackTest.java',instrument/'ExactPhrasePackTest.java')

assert 'versionCode 123' in (root/'app/build.gradle').read_text()
assert 'say exactly this and nothing else' in (java/'SpeechPreferences.java').read_text()
assert 'LocalVoiceService' not in (root/'app/src/main/AndroidManifest.xml').read_text()
for path in java.glob('*.java'):
    for bad in ['android.speech.tts','api.elevenlabs.io','com.k2fsa.sherpa.onnx','TextToSpeech']:
        assert bad not in path.read_text(),(path,bad)
